# required for building jre_lwjgl3glfw with Java 8 while using plugins in app_pojavlauncher that require Java 11
org.gradle.configureondemand=true

android.useAndroidX=true
android.bundle.language.enableSplit=false
# Increase Gradle daemon RAM allocation
org.gradle.jvmargs=-Xmx4096M
android.nonTransitiveRClass=false
android.nonFinalResIds=true
android.suppressUnsupportedCompileSdk=37.0
VERSION_CODE=15
VERSION_NUMBER=4.1.5
VERSION_NAME=

# Compatibility flags for AGP 9.0 upgrade
android.uniquePackageNames=false


